spring.application.name=edge-gateway

server.port=8082

spring.cloud.gateway.server.webflux.routes[0].id = profile

spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/me,/seller-only


