server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/superapp
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: profile
              uri: http://localhost:8081
              predicates:
                - Path=/me,/seller-only,/headers