server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/superapp
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: profile
              uri: http://localhost:8081
              predicates:
                - Path=/me,/seller-only,/headers
            - id: product
              uri: http://localhost:8083
              predicates:
                - Path=/products/**
            - id: order
              uri: http://localhost:8084
              predicates:
                - Path=/orders/**
            - id: support
              uri: http://localhost:8085
              predicates:
                - Path=/support/**
            - id: graphql
              uri: http://localhost:8084
              predicates:
                - Path=/graphql