spring.application.name=order-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/orders
spring.datasource.username=superapp
spring.datasource.password=superapp

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

services.product.url=http://localhost:8083


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Browser-based GraphQL playground, testing ke liye
spring.graphql.graphiql.enabled=true