spring.application.name=order-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/orders
spring.datasource.username=superapp
spring.datasource.password=superapp

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

services.product.url=http://localhost:8083